-- نفّذ هذا الملف من محرر SQL في Supabase
create extension if not exists "pgcrypto";
create type public.app_role as enum ('admin','teacher');
create type public.resource_type as enum ('pdf','word','powerpoint','image','video','link');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, email text, role app_role not null default 'teacher', active boolean not null default true, created_at timestamptz default now());
create table public.settings (id int primary key default 1 check(id=1), platform_name text not null default 'منصة مادة المعلوماتية', teacher_name text, logo text, email text, phone text, updated_at timestamptz default now());
create table public.domains (id uuid primary key default gen_random_uuid(), name text not null, year smallint not null check(year between 1 and 3), branch text not null, term smallint not null check(term between 1 and 3), teacher_id uuid references profiles(id), created_at timestamptz default now());
create table public.units (id uuid primary key default gen_random_uuid(), domain_id uuid not null references domains(id) on delete cascade, name text not null, teacher_id uuid references profiles(id), created_at timestamptz default now());
create table public.resources (id uuid primary key default gen_random_uuid(), title text not null, description text default '', type resource_type not null, url text not null, year smallint not null check(year between 1 and 3), branch text not null, term smallint not null check(term between 1 and 3), domain text not null, unit text not null, teacher text, teacher_id uuid references profiles(id), published boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('resources','resources',true,52428800,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','image/jpeg','image/png','image/webp','video/mp4']) on conflict(id) do nothing;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,name,email) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'name',''),new.email,'أستاذ'),new.email); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
