import { useEffect, useMemo, useState } from 'react';
import { BookOpen, CalendarDays, ChevronDown, ChevronLeft, Code2, ExternalLink, File, FileChartColumn, FileText, Globe2, GraduationCap, KeyRound, Layers3, Link as LinkIcon, LogIn, LogOut, Mail, Menu, MessageCircle, Pencil, Plus, Search, Settings as SettingsIcon, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import { branches, defaultSettings, demoAnnouncements, demoDomains, demoResources, demoTeachers, demoUnits } from './data';
import { demoMode, supabase, supabaseConfigError } from './lib/supabase';
import { invokeAdminUserAction, loadCurriculum, loadTeachers } from './services';
import type { Announcement, AnnouncementType, Domain, LessonIcon, Resource, Settings, Teacher, Unit } from './types';

const emptyLesson: Resource = { id:'', title:'', description:'', type:'link', url:'', viewUrl:'', pdfUrl:'', pptUrl:'', docUrl:'', icon:'book', year:1, branch:branches[1][0], term:1, domain:'', unit:'', teacher:'' };
const emptyAnnouncement: Announcement = { id:'', type:'واجب', title:'', description:'', url:'', year:1, branch:branches[1][0], term:1, createdAt:new Date().toISOString().slice(0,10), teacher:'' };
const lessonIcons: Record<LessonIcon, typeof Globe2> = { globe:Globe2, code:Code2, message:MessageCircle, mail:Mail, book:BookOpen };

type DemoStore = { resources:Resource[]; announcements:Announcement[]; teachers:Teacher[]; settings:Settings; domains:Domain[]; units:Unit[] };

function App() {
  const [resources,setResources] = useState<Resource[]>(demoResources);
  const [announcements,setAnnouncements] = useState<Announcement[]>(demoAnnouncements);
  const [teachers,setTeachers] = useState<Teacher[]>(demoTeachers);
  const [domains,setDomains] = useState<Domain[]>(demoDomains);
  const [units,setUnits] = useState<Unit[]>(demoUnits);
  const [settings,setSettings] = useState<Settings>(defaultSettings);
  const [year,setYear] = useState(1), [branch,setBranch] = useState(branches[1][0]), [term,setTerm] = useState(1), [query,setQuery] = useState('');
  const [admin,setAdmin] = useState(false), [logged,setLogged] = useState(false), [login,setLogin] = useState({email:'admin@example.com',password:'demo123'}), [tab,setTab] = useState('content'), [menu,setMenu] = useState(false);
  const [editingLesson,setEditingLesson] = useState<Resource|null>(null), [editingAnnouncement,setEditingAnnouncement] = useState<Announcement|null>(null);

  useEffect(() => {
    if (demoMode) {
      const saved = localStorage.getItem('informatique-demo-v3');
      if (saved) {
        try {
          const d = JSON.parse(saved) as Partial<DemoStore>;
          setResources(d.resources||demoResources); setAnnouncements(d.announcements||demoAnnouncements); setTeachers(d.teachers||demoTeachers);
          setSettings(d.settings||defaultSettings); setDomains(d.domains||demoDomains); setUnits(d.units||demoUnits);
        } catch { localStorage.removeItem('informatique-demo-v3'); }
      }
    } else {
      Promise.all([
        supabase!.from('resources').select('*').eq('published',true),
        supabase!.from('announcements').select('*').eq('published',true).order('created_at',{ascending:false}),
        loadCurriculum(supabase!)
      ]).then(([r,a,c])=>{
        if(r.data) setResources(r.data.map(fromDbResource));
        if(a.data) setAnnouncements(a.data.map(fromDbAnnouncement));
        setDomains(c.domains); setUnits(c.units);
      }).catch((error)=>alert(`تعذر تحميل البيانات: ${error.message}`));
    }
  },[]);

  const persist=(patch:Partial<DemoStore>={})=>{
    if(!demoMode)return;
    localStorage.setItem('informatique-demo-v3',JSON.stringify({resources,announcements,teachers,settings,domains,units,...patch}));
  };
  const changeYear=(n:number)=>{setYear(n);setBranch(branches[n][0]);};
  const shown=resources.filter(r=>r.year===year&&r.branch===branch&&r.term===term&&`${r.title} ${r.description} ${r.domain} ${r.unit}`.includes(query));
  const grouped=useMemo(()=>Object.entries(shown.reduce<Record<string,Resource[]>>((acc,r)=>{(acc[r.domain]??=[]).push(r);return acc;},{})),[shown]);
  const visibleAnnouncements=announcements.filter(a=>(!a.year||a.year===year)&&(!a.branch||a.branch===branch)&&(!a.term||a.term===term));

  const refreshTeachers=async()=>{if(!demoMode&&supabase)setTeachers(await loadTeachers(supabase));};
  const saveLesson=async(r:Resource)=>{
    if(!r.unit){alert('يجب اختيار وحدة من المنهاج قبل الحفظ.');return;}
    const item={...r,id:r.id||crypto.randomUUID(),title:r.unit,teacher:r.teacher||settings.teacherName,url:r.viewUrl||r.pdfUrl||r.pptUrl||r.docUrl||r.url};
    if(!demoMode&&supabase){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('resources').upsert(toDbResource(item,user?.id));if(error){alert(`تعذر حفظ الدرس: ${error.message}`);return;}}
    const next=r.id?resources.map(x=>x.id===r.id?item:x):[...resources,item];setResources(next);persist({resources:next});setEditingLesson(null);
  };
  const saveAnnouncement=async(a:Announcement)=>{
    const item={...a,id:a.id||crypto.randomUUID(),teacher:a.teacher||settings.teacherName};
    if(!demoMode&&supabase){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('announcements').upsert(toDbAnnouncement(item,user?.id));if(error){alert(`تعذر حفظ الإعلان: ${error.message}`);return;}}
    const next=a.id?announcements.map(x=>x.id===a.id?item:x):[item,...announcements];setAnnouncements(next);persist({announcements:next});setEditingAnnouncement(null);
  };
  const removeLesson=async(id:string)=>{if(!confirm('هل تريد حذف هذا الدرس؟'))return;if(!demoMode&&supabase){const {error}=await supabase.from('resources').delete().eq('id',id);if(error){alert(error.message);return;}}const next=resources.filter(x=>x.id!==id);setResources(next);persist({resources:next});};
  const removeAnnouncement=async(id:string)=>{if(!confirm('هل تريد حذف هذا الإعلان؟'))return;if(!demoMode&&supabase){const {error}=await supabase.from('announcements').delete().eq('id',id);if(error){alert(error.message);return;}}const next=announcements.filter(x=>x.id!==id);setAnnouncements(next);persist({announcements:next});};

  if(admin&&!logged) return <Login login={login} setLogin={setLogin} onSubmit={async()=>{if(demoMode){setLogged(true);return;}if(supabaseConfigError||!supabase){alert(supabaseConfigError);return;}const {error}=await supabase.auth.signInWithPassword({email:login.email.trim(),password:login.password});if(error)alert(`تعذر تسجيل الدخول: ${error.message}`);else {setLogged(true);await refreshTeachers();}}} back={()=>setAdmin(false)}/>;

  return <div className="app"><header><div className="brand"><span className="logo">{settings.logo}</span><div><h1>{settings.platformName}</h1><small>فضاء رقمي للتعلم والمشاركة</small></div></div><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button><nav className={menu?'open':''}><button onClick={()=>{setAdmin(false);setMenu(false)}}><BookOpen/> فضاء الطالب</button><button onClick={()=>{setAdmin(true);setMenu(false)}}><ShieldCheck/> لوحة الإدارة</button></nav></header>
  {demoMode&&<div className="demo">وضع تجريبي محلي — البيانات محفوظة في هذا المتصفح</div>}
  {admin?<Admin resources={resources} announcements={announcements} teachers={teachers} domains={domains} units={units} settings={settings} tab={tab} setTab={setTab} editLesson={setEditingLesson} editAnnouncement={setEditingAnnouncement} removeLesson={removeLesson} removeAnnouncement={removeAnnouncement} setTeachers={(next:Teacher[])=>{setTeachers(next);persist({teachers:next})}} setDomains={(next:Domain[])=>{setDomains(next);persist({domains:next})}} setUnits={(next:Unit[])=>{setUnits(next);persist({units:next})}} setSettings={(next:Settings)=>{setSettings(next);persist({settings:next})}} refreshTeachers={refreshTeachers} logout={()=>{supabase?.auth.signOut();setLogged(false);setAdmin(false)}}/>:<main>
    <section className="hero"><div><span className="eyebrow">التعليم الثانوي</span><h2>دروس المعلوماتية بطريقة أبسط</h2><p>اختر السنة والشعبة والفصل، ثم افتح الدرس بالصيغة التي تناسبك.</p></div><GraduationCap size={110}/></section>
    <section className="filters"><div className="steps"><b>1 السنة</b><ChevronLeft/><b>2 الشعبة</b><ChevronLeft/><b>3 الفصل</b><ChevronLeft/><b>4 الدروس</b></div><div className="grid"><label>السنة الدراسية<select value={year} onChange={e=>changeYear(+e.target.value)}><option value="1">السنة الأولى ثانوي</option><option value="2">السنة الثانية ثانوي</option><option value="3">السنة الثالثة ثانوي</option></select></label><label>الشعبة<select value={branch} onChange={e=>setBranch(e.target.value)}>{branches[year].map(x=><option key={x}>{x}</option>)}</select></label><label>الفصل<select value={term} onChange={e=>setTerm(+e.target.value)}>{[1,2,3].map(x=><option value={x} key={x}>الفصل {x===1?'الأول':x===2?'الثاني':'الثالث'}</option>)}</select></label><label className="search wide-search">البحث<div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن درس..."/></div></label></div></section>
    <Announcements items={visibleAnnouncements}/>
    <section className="lesson-content"><div className="section-title"><h2>الدروس والوحدات التعلمية</h2><p>{shown.length} درس متاح حسب اختيارك</p></div>{grouped.map(([name,items])=><DomainSection key={name} name={name} items={items}/>)}{!grouped.length&&<div className="empty"><Search size={48}/><h3>لا توجد دروس</h3><p>جرّب تغيير السنة أو الشعبة أو الفصل.</p></div>}</section>
  </main>}
  {editingLesson&&<LessonForm value={editingLesson} domains={domains} units={units} close={()=>setEditingLesson(null)} save={saveLesson}/>} {editingAnnouncement&&<AnnouncementForm value={editingAnnouncement} close={()=>setEditingAnnouncement(null)} save={saveAnnouncement}/>}<footer><b>{settings.platformName}</b><span>{settings.teacherName} · {settings.email} · {settings.phone}</span><small>جميع الحقوق محفوظة © {new Date().getFullYear()}</small></footer></div>;
}

function Announcements({items}:{items:Announcement[]}){return <section className="announcements"><div className="section-title"><h2>الإعلانات والواجبات</h2><p>آخر التطبيقات والواجبات والتصحيحات</p></div><div className="announcement-grid">{items.slice(0,6).map(a=><article className="announcement-card" key={a.id}><span className={`announcement-type type-${a.type.replaceAll(' ','-')}`}>{a.type}</span><h3>{a.title}</h3><p>{a.description}</p><div className="announcement-meta"><span><CalendarDays/> {new Date(a.createdAt).toLocaleDateString('ar-DZ')}</span>{a.url&&<a href={a.url} target="_blank" rel="noreferrer">فتح <ExternalLink/></a>}</div></article>)}{!items.length&&<div className="empty compact">لا توجد إعلانات لهذا الاختيار.</div>}</div></section>}
function DomainSection({name,items}:{name:string;items:Resource[]}){return <section className="domain-section"><div className="domain-header"><Layers3/><h2>{name}</h2></div><div className="lesson-list">{items.map((r,i)=><LessonCard key={r.id} r={r} index={i+1}/>)}</div></section>}
function LessonCard({r,index}:{r:Resource;index:number}){const [open,setOpen]=useState(false);const Icon=lessonIcons[r.icon||'book'];const links=[['عرض الدرس',r.viewUrl||r.url,ExternalLink],['ملف PDF',r.pdfUrl,FileText],['عرض PPT',r.pptUrl,FileChartColumn],['مستند DOC',r.docUrl,File]] as const;return <article className="lesson-card"><div className="lesson-info"><span className="lesson-icon"><Icon/></span><div><small>{r.unit}</small><h3>{index}. {r.title}</h3></div></div><div className="lesson-menu"><button aria-expanded={open} onClick={()=>setOpen(!open)}>عرض الدرس <ChevronDown/></button>{open&&<div className="lesson-dropdown">{links.map(([label,url,I],i)=>url?<a key={label} className={i===0?'selected':''} href={url} target="_blank" rel="noreferrer" onClick={()=>setOpen(false)}><I/>{label}</a>:<span key={label} className="disabled"><I/>{label}</span>)}</div>}</div></article>}

function Login({login,setLogin,onSubmit,back}:any){return <div className="login-page"><form onSubmit={e=>{e.preventDefault();onSubmit()}} className="login-box"><span className="big-logo">💻</span><h2>دخول الأساتذة</h2><label>البريد الإلكتروني<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>كلمة المرور<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button className="primary"><LogIn/> تسجيل الدخول</button><button type="button" className="link-btn" onClick={back}>العودة إلى المنصة</button></form></div>}
function Admin({resources,announcements,teachers,domains,units,settings,tab,setTab,editLesson,editAnnouncement,removeLesson,removeAnnouncement,setTeachers,setDomains,setUnits,setSettings,refreshTeachers,logout}:any){return <main className="admin"><aside><h2>لوحة الإدارة</h2>{[['content','الدروس والواجبات',BookOpen],['curriculum','المنهاج',Layers3],['teachers','الأساتذة',Users],['settings','الإعدادات',SettingsIcon]].map(([id,name,I]:any)=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/>{name}</button>)}<button onClick={logout}><LogOut/>تسجيل الخروج</button></aside><section className="admin-content">{tab==='content'&&<><div className="admin-head"><div><h2>إدارة المحتوى</h2><p>أضف درسًا أو واجبًا أو إعلانًا.</p></div><div className="admin-actions"><button className="primary" onClick={()=>editLesson(emptyLesson)}><Plus/> درس جديد</button><button className="secondary" onClick={()=>editAnnouncement(emptyAnnouncement)}><Plus/> واجب / إعلان</button></div></div><h3>الدروس</h3><div className="table-wrap"><table><thead><tr><th>الوحدة</th><th>المجال</th><th>المستوى</th><th>إجراءات</th></tr></thead><tbody>{resources.map((r:Resource)=><tr key={r.id}><td><b>{r.title}</b></td><td>{r.domain}</td><td>{r.year} ثانوي · الفصل {r.term}</td><td><button className="icon" onClick={()=>editLesson(r)}><Pencil/></button><button className="icon danger" onClick={()=>removeLesson(r.id)}><Trash2/></button></td></tr>)}</tbody></table></div><h3 className="admin-subtitle">الواجبات والإعلانات</h3><div className="table-wrap"><table><thead><tr><th>النوع</th><th>العنوان</th><th>الاستهداف</th><th>إجراءات</th></tr></thead><tbody>{announcements.map((a:Announcement)=><tr key={a.id}><td>{a.type}</td><td><b>{a.title}</b></td><td>{a.year?`${a.year} ثانوي · الفصل ${a.term}`:'الجميع'}</td><td><button className="icon" onClick={()=>editAnnouncement(a)}><Pencil/></button><button className="icon danger" onClick={()=>removeAnnouncement(a.id)}><Trash2/></button></td></tr>)}</tbody></table></div></>}{tab==='curriculum'&&<Curriculum domains={domains} units={units} setDomains={setDomains} setUnits={setUnits}/>} {tab==='teachers'&&<Teachers teachers={teachers} setTeachers={setTeachers} refresh={refreshTeachers}/>} {tab==='settings'&&<SettingsForm settings={settings} save={setSettings}/>}</section></main>}

function Curriculum({domains,units,setDomains,setUnits}:{domains:Domain[];units:Unit[];setDomains:(x:Domain[])=>void;setUnits:(x:Unit[])=>void}){
  const [filter,setFilter]=useState({year:1,branch:branches[1][0],term:1});
  const visible=domains.filter(d=>d.year===filter.year&&d.branch===filter.branch&&d.term===filter.term);
  const saveDomain=async(existing?:Domain)=>{const name=prompt(existing?'اسم المجال الجديد':'اسم المجال',existing?.name||'')?.trim();if(!name)return;const item:Domain=existing?{...existing,name}:{id:crypto.randomUUID(),name,...filter};if(!demoMode&&supabase){const {data:{user}}=await supabase.auth.getUser();const payload={id:item.id,name:item.name,year:item.year,branch:item.branch,term:item.term,teacher_id:existing?.teacherId||user?.id};const {error}=await supabase.from('domains').upsert(payload);if(error){alert(error.message);return;}}setDomains(existing?domains.map(d=>d.id===existing.id?item:d):[...domains,item]);};
  const removeDomain=async(domain:Domain)=>{if(!confirm(`حذف المجال «${domain.name}» وكل وحداته؟`))return;if(!demoMode&&supabase){const {error}=await supabase.from('domains').delete().eq('id',domain.id);if(error){alert(error.message);return;}}setDomains(domains.filter(d=>d.id!==domain.id));setUnits(units.filter(u=>u.domainId!==domain.id));};
  const saveUnit=async(domain:Domain,existing?:Unit)=>{const name=prompt(existing?'اسم الوحدة الجديد':'اسم الوحدة',existing?.name||'')?.trim();if(!name)return;const item:Unit=existing?{...existing,name}:{id:crypto.randomUUID(),domainId:domain.id,name};if(!demoMode&&supabase){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('units').upsert({id:item.id,domain_id:item.domainId,name:item.name,teacher_id:existing?.teacherId||user?.id});if(error){alert(error.message);return;}}setUnits(existing?units.map(u=>u.id===existing.id?item:u):[...units,item]);};
  const removeUnit=async(unit:Unit)=>{if(!confirm(`حذف الوحدة «${unit.name}»؟`))return;if(!demoMode&&supabase){const {error}=await supabase.from('units').delete().eq('id',unit.id);if(error){alert(error.message);return;}}setUnits(units.filter(u=>u.id!==unit.id));};
  return <><div className="admin-head"><div><h2>إدارة المنهاج</h2><p>المجالات والوحدات حسب السنة والشعبة والفصل.</p></div><button className="primary" onClick={()=>saveDomain()}><Plus/> إضافة مجال</button></div><div className="panel curriculum-filter form-grid"><label>السنة<select value={filter.year} onChange={e=>{const year=+e.target.value;setFilter({...filter,year,branch:branches[year][0]})}}>{[1,2,3].map(x=><option key={x} value={x}>{x} ثانوي</option>)}</select></label><label>الشعبة<select value={filter.branch} onChange={e=>setFilter({...filter,branch:e.target.value})}>{branches[filter.year].map(x=><option key={x}>{x}</option>)}</select></label><label>الفصل<select value={filter.term} onChange={e=>setFilter({...filter,term:+e.target.value})}>{[1,2,3].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="curriculum-list">{visible.map(domain=><article className="panel curriculum-card" key={domain.id}><div className="curriculum-head"><div><h3>{domain.name}</h3><small>{domain.year} ثانوي · {domain.branch} · الفصل {domain.term}</small></div><div><button className="icon" onClick={()=>saveDomain(domain)}><Pencil/></button><button className="icon danger" onClick={()=>removeDomain(domain)}><Trash2/></button></div></div><div className="unit-list">{units.filter(u=>u.domainId===domain.id).map(unit=><div key={unit.id}><span>{unit.name}</span><span><button className="icon" onClick={()=>saveUnit(domain,unit)}><Pencil/></button><button className="icon danger" onClick={()=>removeUnit(unit)}><Trash2/></button></span></div>)}<button className="secondary add-unit" onClick={()=>saveUnit(domain)}><Plus/> إضافة وحدة</button></div></article>)}{!visible.length&&<div className="empty panel">لا توجد مجالات لهذا الاختيار.</div>}</div></>;
}

function Teachers({teachers,setTeachers,refresh}:{teachers:Teacher[];setTeachers:(x:Teacher[])=>void;refresh:()=>Promise<void>}){
  const [editing,setEditing]=useState<Teacher|null>(null);
  const add=async()=>{const name=prompt('اسم الأستاذ')?.trim();const email=prompt('البريد الإلكتروني')?.trim();const password=prompt('كلمة مرور مؤقتة (8 أحرف على الأقل)')||'';if(!name||!email||password.length<8)return alert('أدخل الاسم والبريد وكلمة مرور من 8 أحرف على الأقل.');if(demoMode){setTeachers([...teachers,{id:crypto.randomUUID(),name,email,role:'teacher',active:true}]);return;}try{await invokeAdminUserAction(supabase!,{action:'create',name,email,password,role:'teacher',active:true});await refresh();}catch(error){alert((error as Error).message)}};
  const save=async(teacher:Teacher)=>{if(demoMode){setTeachers(teachers.map(t=>t.id===teacher.id?teacher:t));setEditing(null);return;}const {error}=await supabase!.from('profiles').update({name:teacher.name,role:teacher.role,active:teacher.active}).eq('id',teacher.id);if(error)return alert(error.message);await refresh();setEditing(null);};
  const remove=async(teacher:Teacher)=>{if(!confirm(`حذف حساب ${teacher.name} نهائيًا؟`))return;if(demoMode){setTeachers(teachers.filter(t=>t.id!==teacher.id));return;}try{await invokeAdminUserAction(supabase!,{action:'delete',userId:teacher.id});await refresh();}catch(error){alert((error as Error).message)}};
  const password=async(teacher:Teacher)=>{const next=prompt(`كلمة المرور الجديدة لـ ${teacher.name}`)||'';if(next.length<8)return alert('كلمة المرور يجب أن تكون 8 أحرف على الأقل.');if(demoMode)return alert('تم تغيير كلمة المرور تجريبيًا.');try{const {data:{user}}=await supabase!.auth.getUser();if(user?.id===teacher.id){const {error}=await supabase!.auth.updateUser({password:next});if(error)throw error;}else await invokeAdminUserAction(supabase!,{action:'password',userId:teacher.id,password:next});alert('تم تغيير كلمة المرور.');}catch(error){alert((error as Error).message)}};
  return <><div className="admin-head"><div><h2>إدارة الأساتذة</h2><p>تعديل الملف والحالة، أو تنفيذ عمليات الحساب الآمنة.</p></div><button className="primary" onClick={add}><Plus/> إضافة أستاذ</button></div><div className="teacher-grid">{teachers.map(t=><div className="panel teacher-card" key={t.id}><div className="avatar">{t.name.slice(-1)}</div><div className="teacher-details"><h3>{t.name}</h3><p>{t.email}</p><span className={`badge ${t.active?'':'inactive'}`}>{t.role==='admin'?'أدمن':'أستاذ'} · {t.active?'نشط':'موقوف'}</span></div><div className="teacher-actions"><button className="icon" title="تعديل" onClick={()=>setEditing(t)}><Pencil/></button><button className="icon" title="تغيير كلمة المرور" onClick={()=>password(t)}><KeyRound/></button><button className="icon danger" title="حذف الحساب" onClick={()=>remove(t)}><Trash2/></button></div></div>)}</div>{editing&&<TeacherForm value={editing} close={()=>setEditing(null)} save={save}/>}</>;
}
function TeacherForm({value,close,save}:{value:Teacher;close:()=>void;save:(t:Teacher)=>void}){const [t,setT]=useState(value);return <div className="modal"><form className="modal-box form" onSubmit={e=>{e.preventDefault();save(t)}}><button type="button" className="close" onClick={close}><X/></button><h2>تعديل الأستاذ</h2><div className="form-grid"><label className="wide">الاسم<input required value={t.name} onChange={e=>setT({...t,name:e.target.value})}/></label><label>الدور<select value={t.role} onChange={e=>setT({...t,role:e.target.value as Teacher['role']})}><option value="teacher">أستاذ</option><option value="admin">أدمن</option></select></label><label>الحالة<select value={t.active?'active':'inactive'} onChange={e=>setT({...t,active:e.target.value==='active'})}><option value="active">نشط</option><option value="inactive">موقوف</option></select></label></div><button className="primary">حفظ التعديلات</button></form></div>}
function SettingsForm({settings,save}:{settings:Settings;save:(s:Settings)=>void}){const [s,setS]=useState(settings);return <form className="panel settings-form" onSubmit={e=>{e.preventDefault();save(s);alert('تم الحفظ')}}><h2>إعدادات المنصة</h2><label>اسم المنصة<input value={s.platformName} onChange={e=>setS({...s,platformName:e.target.value})}/></label><label>الشعار<input value={s.logo} onChange={e=>setS({...s,logo:e.target.value})}/></label><label>اسم الأستاذ<input value={s.teacherName} onChange={e=>setS({...s,teacherName:e.target.value})}/></label><label>البريد<input value={s.email} onChange={e=>setS({...s,email:e.target.value})}/></label><label>الهاتف<input value={s.phone} onChange={e=>setS({...s,phone:e.target.value})}/></label><button className="primary">حفظ</button></form>}
function LessonForm({value,domains,units,close,save}:{value:Resource;domains:Domain[];units:Unit[];close:()=>void;save:(r:Resource)=>void}){const [r,setR]=useState(value);const matchingDomains=domains.filter(d=>d.year===r.year&&d.branch===r.branch&&d.term===r.term);const selectedDomain=matchingDomains.find(d=>d.name===r.domain);const matchingUnits=selectedDomain?units.filter(u=>u.domainId===selectedDomain.id):[];const resetScope=(patch:Partial<Resource>)=>setR({...r,...patch,domain:'',unit:'',title:''});return <div className="modal"><form className="modal-box form" onSubmit={e=>{e.preventDefault();if(!r.unit)return alert('اختر وحدة من القائمة قبل الحفظ.');save(r)}}><button type="button" className="close" onClick={close}><X/></button><h2>{r.id?'تعديل الدرس':'إضافة درس'}</h2><div className="form-grid"><label>السنة<select value={r.year} onChange={e=>{const year=+e.target.value;resetScope({year,branch:branches[year][0]})}}>{[1,2,3].map(x=><option key={x} value={x}>{x} ثانوي</option>)}</select></label><label>الشعبة<select value={r.branch} onChange={e=>resetScope({branch:e.target.value})}>{branches[r.year].map(x=><option key={x}>{x}</option>)}</select></label><label>الفصل<select value={r.term} onChange={e=>resetScope({term:+e.target.value})}>{[1,2,3].map(x=><option key={x}>{x}</option>)}</select></label><label>الأيقونة<select value={r.icon} onChange={e=>setR({...r,icon:e.target.value as LessonIcon})}><option value="book">كتاب</option><option value="globe">متصفح</option><option value="code">أكواد</option><option value="message">تواصل</option><option value="mail">بريد</option></select></label><label className="wide">المجال التعلمي<select required value={r.domain} onChange={e=>setR({...r,domain:e.target.value,unit:'',title:''})}><option value="">{matchingDomains.length?'اختر المجال':'لا توجد مجالات مطابقة — أضفها من المنهاج'}</option>{matchingDomains.map(d=><option key={d.id} value={d.name}>{d.name}</option>)}</select></label><label className="wide">الوحدة التعلمية<select required disabled={!selectedDomain} value={r.unit} onChange={e=>setR({...r,unit:e.target.value,title:e.target.value})}><option value="">{selectedDomain?(matchingUnits.length?'اختر الوحدة':'لا توجد وحدات لهذا المجال'):'اختر المجال أولًا'}</option>{matchingUnits.map(u=><option key={u.id} value={u.name}>{u.name}</option>)}</select></label><label className="wide">رابط عرض الدرس<input type="url" value={r.viewUrl||''} onChange={e=>setR({...r,viewUrl:e.target.value})}/></label><label>رابط PDF<input type="url" value={r.pdfUrl||''} onChange={e=>setR({...r,pdfUrl:e.target.value})}/></label><label>رابط PPT<input type="url" value={r.pptUrl||''} onChange={e=>setR({...r,pptUrl:e.target.value})}/></label><label>رابط DOC<input type="url" value={r.docUrl||''} onChange={e=>setR({...r,docUrl:e.target.value})}/></label></div><button className="primary" disabled={!r.unit}>حفظ الدرس</button></form></div>}
function AnnouncementForm({value,close,save}:{value:Announcement;close:()=>void;save:(a:Announcement)=>void}){const [a,setA]=useState(value);return <div className="modal"><form className="modal-box form" onSubmit={e=>{e.preventDefault();save(a)}}><button type="button" className="close" onClick={close}><X/></button><h2>{a.id?'تعديل الإعلان':'إضافة واجب أو إعلان'}</h2><div className="form-grid"><label>النوع<select value={a.type} onChange={e=>setA({...a,type:e.target.value as AnnouncementType})}><option>تطبيق</option><option>واجب</option><option>تصحيح واجب</option></select></label><label>العنوان<input required value={a.title} onChange={e=>setA({...a,title:e.target.value})}/></label><label className="wide">الوصف<textarea required value={a.description} onChange={e=>setA({...a,description:e.target.value})}/></label><label>السنة<select value={a.year||''} onChange={e=>{const y=e.target.value?+e.target.value:undefined;setA({...a,year:y,branch:y?branches[y][0]:undefined})}}><option value="">كل السنوات</option>{[1,2,3].map(x=><option key={x} value={x}>{x} ثانوي</option>)}</select></label>{a.year&&<label>الشعبة<select value={a.branch} onChange={e=>setA({...a,branch:e.target.value})}>{branches[a.year].map(x=><option key={x}>{x}</option>)}</select></label>}<label>الفصل<select value={a.term||''} onChange={e=>setA({...a,term:e.target.value?+e.target.value:undefined})}><option value="">كل الفصول</option>{[1,2,3].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">الرابط (اختياري)<input type="url" value={a.url||''} onChange={e=>setA({...a,url:e.target.value})}/></label></div><button className="primary">حفظ الإعلان</button></form></div>}

function fromDbResource(r:any):Resource{return {...r,viewUrl:r.view_url,pdfUrl:r.pdf_url,pptUrl:r.ppt_url,docUrl:r.doc_url};}
function toDbResource(r:Resource,teacherId?:string){return {id:r.id,title:r.title,description:r.description,type:r.type,url:r.url,view_url:r.viewUrl||null,pdf_url:r.pdfUrl||null,ppt_url:r.pptUrl||null,doc_url:r.docUrl||null,icon:r.icon||'book',year:r.year,branch:r.branch,term:r.term,domain:r.domain,unit:r.unit,teacher:r.teacher,teacher_id:teacherId,published:true};}
function fromDbAnnouncement(a:any):Announcement{return {id:a.id,type:a.type,title:a.title,description:a.description,url:a.url,year:a.year,branch:a.branch,term:a.term,createdAt:a.created_at,teacher:a.teacher};}
function toDbAnnouncement(a:Announcement,teacherId?:string){return {id:a.id,type:a.type,title:a.title,description:a.description,url:a.url||null,year:a.year||null,branch:a.branch||null,term:a.term||null,teacher:a.teacher,teacher_id:teacherId,published:true};}

export default App;
